repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        files: ^(tests|src|scripts|serve)/.*\.py$
      - id: ruff-format
        files: ^(tests|src|scripts|serve)/.*\.py$
